version: '3.4'

services:
  omoqochallengeapi:
    build: /api
    container_name: omoqochallenge-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8080:80

  omoqochallengeweb:
    build: /client/omoqo-challenge-web
    container_name: omoqochallenge-web
    ports:
      - 4200:80
    links:
      - omoqochallengeapi
